### ISSUE TITLE
Misspelling of integration

### ISSUE THREAD

**Issue by kyt999** [lacework/python-sdk#69]
Throughout the repo the word integration is spelt interation

**Comment by alannix-lw** [comment]
Hi @kyt999, thanks for opening this issue!  Can you kindly point me to an example of this misspelling?  I only see it in the initial commit from ~2 years ago, and it was fixed in the next commit here: https://github.com/lacework/python-sdk/commit/744751b65fd85b18977f4b772968913ee41c7a28

Also a `git grep -n interation` returns no results for the latest releases, so curious where you're seeing it.

**Comment by kyt999** [comment]
Hey @alannix-lw , here you go:

<img width="1649" alt="Screen Shot 2022-05-17 at 3 43 28 PM" src="https://user-images.githubusercontent.com/55297216/168897009-380715e9-6f4a-4017-b93d-0a526073aeca.png">

**Comment by alannix-lw** [comment]
🤦‍♂️  Thank you!  It's been fixed!
